config/routes.rb
Rails.application.routes.draw do

resources :todos

get 'help' => 'pages#help'
get '/about' => 'pages#about'

root 'todos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :user, presence: true
  validates :email, presence: true
  
  has_many :todos
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
  
  def about
    
  end
  
  def help
    
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, except: [:index, :new, :create, ]
  
  def index
    @todos = Todo.all
  end
  
  def show
  end
  
  def new
   @todo = Todo.new
  end
  
  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Todo saved successfully"
      redirect_to todo_path(@todo)
    else
      flash[:notice] = "Please try again"
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo has been successfully updated"
      redirect_to todo_path(@todo)
    else
      flash[:notice] = "Please try again"
      render 'edit'
    end
  end
  
  def destroy
    @todo.destroy
    flash[:notice] = "Todo has been deleted successfully"
    redirect_to root_path
  end
  
  private
  
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
  
  def set_todo
    @todo = Todo.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/flash' %>
    
    <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/help.html.erb
<h1>Help Page</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/shared/_errors.html.erb
<% if @todo.errors.any? %>
  <h2>Following errors prevented this from saving</h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>

<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</p>


<%= f.submit ( f.object.new_record? ? "Create Todo" : "Update Todo") %>

<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= render 'shared/errors' %>

<%= render 'form' %>

<br />
<%= link_to 'Back', todo_path(@todo) %>

app/views/todos/index.html.erb
<h1>All Todos</h1>

<% @todos.each do |todo| %>
  
  <ul>
    <li>Name: <%= link_to todo.name, todo_path(todo) %></li>
  </ul>

<% end %>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%= render 'shared/errors' %>

<%= render 'form' %>

<br />

<%= link_to 'Back', root_path %>

app/views/todos/show.html.erb
<h1>Todo</h1>

<h3>Name: <%= @todo.name %></h3>
<p>Description: <%= @todo.description %></p>
<%= link_to 'Edit', edit_todo_path(@todo) %>
<%= link_to 'Delete', todo_path(@todo), method: :delete, data: {confirm: "Are you sure?" } %>
<%= link_to 'Back', root_path %>